### ISSUE TITLE
关于数据集的疑问

### ISSUE THREAD

**Issue by MaoXinn** [nju-websoft/MultiKE#1]
如果我没有理解错误的话，该论文的数据集是复用BootEA的，并且在论文中好像也没有对数据进行修改的描述。
根据我对数据集的观察，YG和WD的实体名称好像是一模一样的？WD数据集给出了两个每个实体的链接，虽然我没有一个一个爬下来看，但是点开大部分都是一样的。YG则是只给了dbp的链接，yago里的实体只有名称，我比了一下是完全一致的。
但是论文中最重要的部分实际上就是name这个view，如果实体的name完全一致的话，系统不就失去了意义？ 亦或是我严重误解了论文？

**Comment by sunzequn** [comment]
这篇论文的主要贡献在于提出了一个面向实体对齐的多视图表示学习框架，并探索了多视图组合的方法，使得视图之间可以互相增强，以达到更好的性能，我们的实验结果也验证了这一点。实际上，我们的框架并不局限于论文中尝试的名称、关系和属性三个视图，它具有很好的拓展性，此外每个视图下的表示学习方法也不仅限于论文中所尝试的那些，其他方法也是可以集成进来的。

对于DWY100K数据集，由于DBpedia、Wikidata和YAGO的主要数据来源都是Wikipedia，所以很多实体有相似或者相同的名称。论文表2中名称视图的结果也印证了这一点。但是本文提出的基于表示学习的名称对齐，并不只是能处理这种情况，对于异质性更大的对齐场景，比如跨语言实体对齐，我们相信基于跨语言词向量的方法也可以处理，这也正是表示学习方法相较于传统方法的优势所在。实际上，我们在论文的未来工作中也提到了这一点。最后，我们也欢迎大家在别的数据集上进行进一步测试。
