### ISSUE TITLE
Learned literal embeddings

### ISSUE THREAD

**Issue by LiuYuLOL** [nju-websoft/MultiKE#11]
Hi, thanks for the great work which inspires me a lot.

I just follow the proposed autoencoder to learn the representations of any literals. However, I found that the embeddings of these literals are more like ''features (1 or -1)'', most of the values are ''marginal'', like [-1.0, 0.9999, -1.0, 1.0, 0.9626, -1.0, ...]. 

Ideally, I think embeddings are spread over the space,  like word2vec, e.g., [0.31, 0.01, 0.1, -0.5, ...]. But I'm not so certain and not familiar with autoencoders. So I just wonder whether these embeddings are the correct and good for KG alignment? 

In the attribute view and name view, will the value (and name) embeddings be effected as traditional features (if the embeddings are marginal)?

Cheers,
Yu

**Comment by sunzequn** [comment]
Hi,

Thank you for your interest in our work! 

I think this is a very interesting finding and your thinking is also rational. I will look into this phenomenon. In my view, the marginal embeddings are not the most ideal for entity alignment. But in multi-view embedding, the final performance is determined by all view-specific embeddings. You can further study this and improve the issue. This is very interesting for entity alignment. 

Zequn Sun
