### ISSUE TITLE
我在运行该程序时，出现了很多问题。缺少一些文件，能否把运行出结果的代码上传一下呢

### ISSUE THREAD

**Issue by zhang-9l** [nju-websoft/MultiKE#17]
1）在.json文件中我对路径进行了修改（磁盘的路径），不知是否正确
 

2）word2vec_path在您的代码文件里是没有的，然后我从网上下载了一个,不知与您之前的是否一样
 
 
3）在MultiKE-CSL中使用了output中的文件（作为参数传入），对于这个路径下的文件是用来干什么的，我一直没有搞清楚，因为作为参数传入的话不应该有数据吗？可是这个里面是没有东西的呢
 
4）在data_model文件里literal_vectors.npy和literals.txt文件是什么？我没有找到
 
5)这个是我按照您的readme运行的命令。但是出不来结果，老师是不是这个代码文件不全呢？
 
5）一运行到关于wiki-new这个文件就出现问题
 

[

**Comment by sunzequn** [comment]
同学你好，

感谢你对我们工作的关注。这个代码应该是没有问题的，只是需要配置好需要的文件。负责代码的学弟已经毕业了，我暂时没有精力去维护，你可以参考[OpenEA](https://github.com/nju-websoft/OpenEA)里面MultiKE的实现，应该没有问题。

**Comment by zhang-9l** [comment]
好的 感谢学长/学姐的回复
