### ISSUE TITLE
关于SSL与ITC的疑问

### ISSUE THREAD

**Issue by helenxu** [nju-websoft/MultiKE#2]
你好~不是很明白论文中关于SSL与ITC部分的描述，例如SSL的损失函数中的Z^{(i)}是如何获得的，需要优化的参数是什么？

**Comment by sunzequn** [comment]
Z是映射矩阵，一开始随机初始化，然后参与公式18的loss，和各视图下的实体向量等参数一起优化

**Comment by helenxu** [comment]
了解了，感谢如此迅速的回答~ 期待你们的代码
