### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by Kuzzzz** [nju-websoft/MultiKE#3]
当模型跑到alignment.py中的multiprocessing.Pool()时报OSError: [Errno 12] Cannot allocate memory。我用的是8G的Tesla P4,请问您当时在训练模型的时候用的是什么样的显卡？

**Comment by sunzequn** [comment]
你好，这个地方似乎是cpu计算的，测试的时候我把实体表示矩阵从gpu拿出来了。所以可能是cpu内存不够了吧。我们训练的机器是128g cpu内存。

**Comment by Kuzzzz** [comment]
> 你好，这个地方似乎是cpu计算的，测试的时候我把实体表示矩阵从gpu拿出来了。所以可能是cpu内存不够了吧。我们训练的机器是128g cpu内存。

好的，十分感谢，那我去集群上试一试。
