### ISSUE TITLE
Question bout relation and attribute identity inference

### ISSUE THREAD

**Issue by helenxu** [nju-websoft/MultiKE#4]
I read from section 4.2 of the paper and got the sentence above equation (15): "We consider two kinds of similarity: name similarity based on literal embeddings and semantic similarity based on  relation embeddings."

However, after carefully going through the code, I can't find where was "name similarity base on literal embeddings" implemented. Instead, I found that the Levenshtein similarity between the names are used: (in predicate_alignment.py)

![code](https://user-images.githubusercontent.com/3434891/64260479-84e4b500-cf5d-11e9-8787-bd0d8f7fb8f7.png)

Am I misunderstanding anything here?

**Comment by shilan910** [comment]
Thank you for pointing this out.
I tried the two ways you mentioned, Levenshtein similarity and name similarity base on literal embeddings. I found that the latter performed slightly better. Therefore, I ended up using name similarity base on literal embeddings.
However, in this version, I ignore this detail. I will correct this problem as soon as possible and upload another version that is consistent with the paper description.
Thank you again.
