### ISSUE TITLE
一些小的疑问

### ISSUE THREAD

**Issue by Kuzzzz** [nju-websoft/MultiKE#5]
初次接触实体对齐任务，有一些小的疑问还请赐教：
1.DBP_WD数据集中rel_triples中代表的是e1e2之间的关系，attr_triples中代表的是e和attr之间的关系，关于ent_links里代表的是什么意思？
2.还有论文中的模型的输入是kg1和kg2的name view / relation view / attr view，那模型的输出是什么？
3.还有实验中的评价指标是什么意思，mean score是由什么计算得到的？

**Comment by shilan910** [comment]
1. attr_triples可表示为 (entity, attribute, value)，例如 (达·芬奇, 出生日期, 1452年4月15日)；ent_links表示的是两个KG之间的对齐实体对；
2. MultiKE的输出是两个KG之间潜在对齐的实体对集合；
3. 实验中的评价指标是实体对齐任务中常见的Hits@k，mean rank(MR) 以及 mean reciprocal rank(MRR)；Hits@k是指正确结果的排名处于在前k个结果中的比例；MR是指正确结果排名的平均值；MRR是指正确结果排名倒数的平均值。

**Comment by Kuzzzz** [comment]
> 1. attr_triples可表示为 (entity, attribute, value)，例如 (达·芬奇, 出生日期, 1452年4月15日)；ent_links表示的是两个KG之间的对齐实体对；
> 2. MultiKE的输出是两个KG之间潜在对齐的实体对集合；
> 3. 实验中的评价指标是实体对齐任务中常见的Hits@k，mean rank(MR) 以及 mean reciprocal rank(MRR)；Hits@k是指正确结果的排名处于在前k个结果中的比例；MR是指正确结果排名的平均值；MRR是指正确结果排名倒数的平均值。

十分感谢您的回复。
