### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by Jexceed** [nju-websoft/MultiKE#7]
I find that the last characters of predicts in Wikidata are missed in your dataset
(file: Project_dir/BootEA_datasets/BootEA_DBP_WD_100K/predicate_local_name_2)

For example:
```
In dataset: http://www.wikidata.org/entity/P1476	titl
Real name in Wikidata: http://www.wikidata.org/entity/P1476	title
```
Could you fix the problem and update the dataset?

**Comment by shilan910** [comment]
Thank you for pointing this out. I have updated the fixed dataset.

**Comment by Jexceed** [comment]
Thanks
