### ISSUE TITLE
关于使用的word embedding

### ISSUE THREAD

**Issue by acharkq** [nju-websoft/MultiKE#8]
![image](https://user-images.githubusercontent.com/34520988/70029424-0fcb5f00-15e2-11ea-8a1b-2d0717e4e76c.png)

运行时报了以上错误。请问你使用的wikinews embedding是来自这个[网站](https://fasttext.cc/docs/en/english-vectors.html)吗

**Comment by shilan910** [comment]
是你说的这个网站。
但从截图来看，报错应该是因为args.json中词向量文件的路径不对，即word2vec_path有问题，应该换成你自己的文件路径。

**Comment by acharkq** [comment]
这么快回复十分感谢！

你们的github仓库中中没有word embedding哦
